### ISSUE TITLE
VisualStudio project - debugging working directory

### ISSUE THREAD

**Issue by markfinal** [markfinal/BuildAMation#244]
Some libraries assume that the current working directory is where the executable is.

By default, VisualStudio sets the ProjectDir as the working directory for debugging, which is not where it should be - should be TargetDir.

How is this set?

**Comment by markfinal** [comment]
A quick test seems to suggest the .suo binary file contains this.

**Comment by markfinal** [comment]
Immediate issues I see:
1) I haven't yet found a file format description
2) Regenerating the .suo might delete other user specified details after the .sln has been loaded - so perhaps it never changes once existing. Might need a force mode.

**Comment by joshmartel** [comment]
Not sure if this is useful to you, but if you enter a path in the "Working Directory" option of the Debugging section of the Configuration Properties inside Visual Studio, it's saved to the vcxproj.user file as <LocalDebuggerWorkingDirectory>.

**Comment by markfinal** [comment]
@joshmartel Thanks for the info. I've just tried this in the VS2015 (Community) IDE but I'm not seeing any sign of the working directory in my project's <projectname>.vcxproj.user file.

Which version of VisualStudio have you seen this in?

**Comment by joshmartel** [comment]
In 2015 Community, but I believe it's been this way since vcxproj.user was introduced.

Make sure you actually write the project after modifying the settings. It's not saved immediately. File->Save All does it for me.

**Comment by markfinal** [comment]
@joshmartel I just discovered the magic 'quit VS' step, just before reading your edit. Very odd, thanks Microsoft!

I'll try writing this file in a BAM VSSolution project generation build, to see if the IDE honours it. If it does, I'll expose it in the API somewhere sensible.

Thanks for the tip!
I see that CMake doesn't really expose this http://stackoverflow.com/questions/23950887/does-cmake-offer-a-method-to-set-the-working-directory-for-a-given-build-system

**Comment by markfinal** [comment]
@joshmartel Seems to work in a quick test. I'll keep on it.

**Comment by markfinal** [comment]
@joshmartel Just wanted to say thanks for the tip on how to implement this in VS. I also threw in Xcode support too (somewhat simpler to find where that went, than in VS!). I'll make a v1.0.3 beta containing this change soon.

Are you using BuildAMation for any software development?

I would be happy to receive more feedback/requests/discussion if you find you can't do something with it.

**Comment by joshmartel** [comment]
I have played with it a bit for some personal projects after being disappointed in premake, cmake, etc, and I really like it! I think I found BAM by googling "premake/cmake alternatives" that turned up a SO or reddit post that listed it. My C# experience combined with your starter doc made it reasonably easy to figure out how to use, and Resharper automatic decompile helped me figure out a few confusing things when I was exploring. For example, BAM defaults to warning level 1, which doesn't work for me because I want max warnings on everything. It was easy to discover that there was a warning level compiler setting in the visual studio compiler subclass, but it took me a while to figure out exactly how to modify it. Several times, I managed to either modify a setting that wasn't sticky or to get a ref to an interface that didn't downcast the way I expected.

I know this feedback isn't very useful, but I'll try to write something more detailed if I can find time.

Overall, please keep up the great work! Project configuration with actual code would be amazing as opposed to the various half-busted scripting required by existing systems.

**Comment by markfinal** [comment]
@joshmartel All feedback is useful, and what you'd said has justified the reasons for both making BAM but also making it open source. So thank you. I'm glad you like it.

So yes, the VisualCCommon package does default the warning level to 1, which intentionally matches the default in the compiler.
But I agree that it's far more useful to bump up the warning level in real software development.

So you have the choice of the local patches per module, which is what you did from your description. Or, there is the Bam.Core.ISitePolicy interface.
If you implement this interface, including it into your package build, then it hooks into the settings classes,  allowing you to modify the defaults, before your modules see them. So there's no need for local patches on each and every module if you want a different 'default'. The interface was created with the thought that individuals or companies have their own idea of a default, and those I chose in the original packages don't suit everyone.

I use a custom site policy in my own software development, and have warning level 4 set as default everywhere. Ditto on OSX and Linux, where I have -Wall, -Wextra and -pedantic set as default.

I've written an example to illustrate this, which will appear in v1.0.3. See https://github.com/markfinal/BuildAMation/blob/v1.0/tests/ChangeDefaultSettings/bam/Scripts/ChangeDefaultSettings.cs

If you're interested, I'm well up for others working on BAM, either the core, or implementing their own open source package repositories.

If you're also willing, I'd definitely appreciate a short testimonial of why you use BAM for builds, that I could publish on the buildamation.com website.

Let me know if any of this is of interest to you. You can reach me by email at markfinal@hotmail.com.
Thanks.
